import os
import logging
import unittest

import matplotlib.pyplot as plt
import numpy as np
import psr_formats

from pfb import fft_windows
from pfb.format_handler import PSRFormatSynthesizer

current_dir = os.path.dirname(os.path.abspath(__file__))
data_dir = os.path.join(current_dir, "test_data")

fir_file_path = os.path.join(
    data_dir, "Prototype_FIR.4-3.8.80.mat")

# data_dir = ("/home/SWIN/dshaff/mnt/ozstar/projects/"
#             "PST_Matlab_dspsr_PFB_inversion_comparison/data")


input_file_paths = [os.path.join(data_dir, file_name) for file_name in
                    ["polyphase_analysis.complex_sinusoid.dump",
                     "polyphase_analysis.time_domain_impulse.dump"]]

matlab_file_paths = [os.path.join(data_dir, file_name) for file_name in
                     ["polyphase_synthesis_alt.complex_sinusoid.dump",
                      "polyphase_synthesis_alt.time_domain_impulse.dump"]]

nchan = 8


class TestPFBSynthesisValidation(unittest.TestCase):
    """
    Validate PFB against data generated by reference Matlab code
    """

    def test_vs_matlab(self):
        synthesizer = PSRFormatSynthesizer(
            input_overlap=32,
            fft_window=fft_windows.tukey_window(1024, 32),
            apply_deripple=True,
            input_fft_length=1024
        )
        for input_file_path, matlab_file_path in zip(input_file_paths,
                                                     matlab_file_paths):
            input_file = psr_formats.DADAFile(input_file_path).load_data()
            input_file_name = os.path.basename(input_file.file_path)
            matlab_file = psr_formats.DADAFile(matlab_file_path).load_data()
            output_file = synthesizer(
                input_file,
                output_dir=data_dir,
                output_file_name=f"pfb_synthesis.{input_file_name}",
            )

            allclose = np.allclose(
                matlab_file.data.flatten(),
                output_file.data.flatten(),
                atol=1e-5
            )

            if not allclose:
                self._detailed_comparison(matlab_file, output_file)
                plt.show()

            self.assertTrue(allclose)

    def _plot_input_data(self, input_file):

        fig, axes = plt.subplots(1, 1)
        axes.plot(input_file.data[:, 0, 0].real)
        axes.plot(input_file.data[:, 0, 0].imag)
        axes.set_title('Input data')

    def _detailed_comparison(self, expected_file, test_file):

        fig, axes = plt.subplots(nchan, 6)

        z1 = np.real
        z2 = np.imag
        # z1 = np.abs
        # z2 = np.angle
        axes[0, 0].set_title('Expected complex component 1')
        axes[0, 1].set_title('Test complex component 1')
        axes[0, 2].set_title('Diff complex component 1')
        axes[0, 3].set_title('Expected complex component 2')
        axes[0, 4].set_title('Test complex component 2')
        axes[0, 5].set_title('Diff complex component 2')

        print(expected_file.data.shape)
        print(test_file.data.shape)

        for ichan in range(nchan):
            e_ichan = expected_file.data[:, ichan, 0][:]
            t_ichan = test_file.data[:, ichan, 0][:]
            axes[ichan, 0].plot(z1(e_ichan))
            axes[ichan, 1].plot(z1(t_ichan))
            axes[ichan, 2].plot(np.abs(z1(t_ichan) - z1(e_ichan)))

            axes[ichan, 3].plot(z2(e_ichan))
            axes[ichan, 4].plot(z2(t_ichan))
            axes[ichan, 5].plot(np.abs(z2(t_ichan) - z2(e_ichan)))

            for i in range(6):
                # axes[ichan, i].set_xlim([0, 100])
                axes[ichan, i].grid(True)


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    logging.getLogger("matplotlib").setLevel(logging.ERROR)
    unittest.main()
